import type { MetadataRoute } from 'next';

// PWA manifest — installable as a standalone app on iOS/Android home
// screens. `display: standalone` strips the browser chrome, so when a
// user taps the icon the app opens fullscreen (no URL bar).
//
// Icons are generated by scripts/generate-pwa-icons.mjs from the master
// logo at public/logo/mark.jpg. Re-run it whenever the logo changes:
//   node scripts/generate-pwa-icons.mjs
// Chrome's installability check VERIFIES that each icon's actual file
// dimensions match the declared `sizes` — if they don't (e.g. claiming
// 192x192 but serving a 1024x1024 file), the install banner silently
// never fires. That's why we keep dedicated files per size instead of
// pointing every entry at the same image.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'AllureTV — Romance Audiobooks',
    short_name: 'AllureTV',
    description:
      'Sensual romance audiobooks and ebooks. Listen, read, and watch.',
    start_url: '/?source=pwa',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0a0710',
    theme_color: '#0a0710',
    lang: 'en',
    categories: ['entertainment', 'books', 'lifestyle'],
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-maskable-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
